import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { CommonModule } from '@angular/common';

interface FAQItem {
  id: string;
  category: string;
  question: string;
  answer: string;
}

@Component({
  selector: 'app-faq',
  imports: [FormsModule, RouterModule, MatIconModule, CommonModule],
  templateUrl: './faq.html',
  styleUrl: './faq.css',
})
export class FAQ {
  searchQuery = '';
  openFAQs = signal<Set<string>>(new Set());

  faqs: FAQItem[] = [
    // Getting Started
    {
      id: '1',
      category: 'getting-started',
      question: 'What is My Author\'s Hub?',
      answer: 'My Author\'s Hub is a comprehensive publishing platform that empowers writers to publish, market, and distribute their books worldwide. We provide services including ISBN generation, royalty management, book distribution, and author-publisher collaboration tools.',
    },
    {
      id: '2',
      category: 'getting-started',
      question: 'How do I get started as an author?',
      answer: 'To get started, you need to create an account and complete your author profile. Once approved, you can create titles, work with publishers, and begin the publishing process. You can also be invited by a publisher using an invitation code.',
    },
    {
      id: '3',
      category: 'getting-started',
      question: 'How do I get started as a publisher?',
      answer: 'Publishers must register and complete their profile with business details. After approval by the platform administrators, you can invite authors, manage titles, generate ISBNs, and handle distribution. The approval process ensures quality and compliance.',
    },
    {
      id: '4',
      category: 'getting-started',
      question: 'What services does My Author\'s Hub provide?',
      answer: 'We offer ISBN generation (both print and ebook), book publishing and distribution, royalty tracking and payments, marketing tools, author-publisher collaboration features, order management, and both digital and print book distribution across multiple platforms.',
    },

    // Account & Profile
    {
      id: '5',
      category: 'account',
      question: 'How do I create an account?',
      answer: 'Click on the registration link and provide your email, name, and other required information. You\'ll need to verify your email address to activate your account. Authors and publishers have separate registration processes.',
    },
    {
      id: '6',
      category: 'account',
      question: 'Can I have both an author and publisher account?',
      answer: 'Yes, you can have both roles, but they require separate registrations and approvals. Each role has different permissions and access levels within the platform.',
    },
    {
      id: '7',
      category: 'account',
      question: 'How do I update my profile information?',
      answer: 'Navigate to your profile page from the dashboard. You can update personal information, contact details, bank information, and address. Some changes may require verification before they take effect.',
    },
    {
      id: '8',
      category: 'account',
      question: 'What should I do if I forget my password?',
      answer: 'Click on "Forgot Password" on the login page. Enter your registered email address, and you\'ll receive instructions to reset your password. Follow the link in the email to create a new password.',
    },
    {
      id: '9',
      category: 'account',
      question: 'How do I deactivate or delete my account?',
      answer: 'You can request account deactivation through your profile settings. Note that deactivation may affect active titles, royalties, and ongoing contracts. Contact support for assistance with account deletion.',
    },

    // Publishing
    {
      id: '10',
      category: 'publishing',
      question: 'How do I create a new title?',
      answer: 'Navigate to the Titles section and click "Create New Title." Fill in all required information including title name, description, genre, category, and other metadata. You can save drafts and complete the process in multiple steps.',
    },
    {
      id: '11',
      category: 'publishing',
      question: 'What is an ISBN and how do I get one?',
      answer: 'An ISBN (International Standard Book Number) is a unique identifier for your book. We provide ISBN generation services for both print and ebook formats. You can either provide your own ISBN or request one to be generated by our platform. ISBNs are essential for book distribution and sales tracking.',
    },
    {
      id: '12',
      category: 'publishing',
      question: 'What information do I need to publish a book?',
      answer: 'You\'ll need: title name, author information, genre and category, book description, cover image, manuscript files, page count, edition information, pricing details, distribution preferences, and royalty agreements. The platform guides you through each step.',
    },
    {
      id: '13',
      category: 'publishing',
      question: 'How long does the publishing process take?',
      answer: 'The timeline varies based on title approval, ISBN processing, and distribution setup. Typically, after all information is submitted and approved, titles can be published within 2-4 weeks. Complex cases or additional requirements may take longer.',
    },
    {
      id: '14',
      category: 'publishing',
      question: 'What are the different distribution types?',
      answer: 'We offer multiple distribution options: MAH (platform distribution), National, Hardbound National, Global, National Prime, and Audiobook distribution. Each has different requirements, pricing, and reach. Your publisher can help you choose the best options.',
    },
    {
      id: '15',
      category: 'publishing',
      question: 'Can I update my book information after publishing?',
      answer: 'Yes, but updates require approval through our ticket system. You can request updates to pricing, royalties, distribution, media files, and other details. Major changes may require admin approval before they take effect.',
    },
    {
      id: '16',
      category: 'publishing',
      question: 'What file formats are accepted for manuscripts?',
      answer: 'We accept common document formats including PDF, DOC, DOCX, and EPUB. For best results, ensure your files meet our quality standards and formatting guidelines. Check the upload requirements before submitting.',
    },

    // Payments & Royalties
    {
      id: '17',
      category: 'payments',
      question: 'How are royalties calculated?',
      answer: 'Royalties are calculated based on your agreement with the publisher and platform margins. For print books, royalties are calculated after deducting printing costs and platform margins from the MRP. For ebooks, royalties are calculated from the net sales price after platform margins. The exact percentage is determined by your publishing agreement.',
    },
    {
      id: '18',
      category: 'payments',
      question: 'When will I receive my royalty payments?',
      answer: 'Royalty payments are processed according to your publishing agreement schedule. Typically, payments are made monthly or quarterly after sales are verified. You can track your earnings in the Royalties section of your dashboard.',
    },
    {
      id: '19',
      category: 'payments',
      question: 'How do I set up payment information?',
      answer: 'Navigate to your profile and add your bank details. You\'ll need to provide account number, IFSC code, bank name, and account holder name. This information must be verified before payments can be processed.',
    },
    {
      id: '20',
      category: 'payments',
      question: 'Can I view my earnings and sales data?',
      answer: 'Yes, you can view detailed earnings reports, sales data, and royalty breakdowns in the Royalties and Earnings sections. Reports show earnings by title, platform, and time period. You can also download reports for your records.',
    },
    {
      id: '21',
      category: 'payments',
      question: 'What payment methods are supported?',
      answer: 'We process payments through bank transfers to verified bank accounts. All payments are made in INR (Indian Rupees). International authors may need to provide additional documentation for payment processing.',
    },
    {
      id: '22',
      category: 'payments',
      question: 'How are printing costs calculated?',
      answer: 'Printing costs are calculated based on page count, paper quality, binding type, size, and quantity. The platform provides a printing calculator to estimate costs. Publishers can set custom printing prices or use standard calculations.',
    },
    {
      id: '23',
      category: 'payments',
      question: 'What is a wallet and how does it work?',
      answer: 'Your wallet is a virtual account where earnings are credited. You can view your wallet balance, transaction history, and request payouts. Payouts are processed after verification and approval according to your payment schedule.',
    },

    // Technical Support
    {
      id: '24',
      category: 'technical',
      question: 'I\'m having trouble uploading files. What should I do?',
      answer: 'Ensure your files meet size and format requirements. Check your internet connection and try using a different browser. If problems persist, contact technical support with details about the error message you\'re seeing.',
    },
    {
      id: '25',
      category: 'technical',
      question: 'How do I raise a ticket for updates or issues?',
      answer: 'Navigate to the relevant section (Title, Author, Publisher) and use the "Raise Ticket" or "Raise Update Ticket" option. Fill in all required information and submit. You can track ticket status in the Update Tickets section.',
    },
    {
      id: '26',
      category: 'technical',
      question: 'What browsers are supported?',
      answer: 'We support modern browsers including Chrome, Firefox, Safari, and Edge. For best performance, use the latest version of your browser. Some features may require JavaScript to be enabled.',
    },
    {
      id: '27',
      category: 'technical',
      question: 'How do I download my ISBN barcode?',
      answer: 'Once your ISBN is approved, you can download the barcode from the ISBN list page. Click on the download option next to your ISBN. The barcode is provided in a standard format suitable for printing on book covers.',
    },
    {
      id: '28',
      category: 'technical',
      question: 'Can I export my data?',
      answer: 'Yes, you can export various reports including title lists, royalty reports, sales data, and transaction history. Look for the export or download options in the respective sections of your dashboard.',
    },
    {
      id: '29',
      category: 'technical',
      question: 'What should I do if I encounter an error?',
      answer: 'Note the error message and the action you were performing. Try refreshing the page or logging out and back in. If the issue persists, contact support with screenshots and details. Our technical team will investigate and resolve the issue.',
    },
  ];

  filteredFAQs: FAQItem[] = this.faqs;

  getFilteredFAQs(category: string): FAQItem[] {
    if (!this.searchQuery.trim()) {
      return this.faqs.filter((faq) => faq.category === category);
    }

    const query = this.searchQuery.toLowerCase();
    return this.faqs.filter(
      (faq) =>
        faq.category === category &&
        (faq.question.toLowerCase().includes(query) ||
          faq.answer.toLowerCase().includes(query))
    );
  }

  filterFAQs() {
    // This method is called on input, but we filter in getFilteredFAQs
    // to ensure real-time search works with categories
  }

  toggleFAQ(id: string) {
    const current = this.openFAQs();
    const updated = new Set(current);
    if (updated.has(id)) {
      updated.delete(id);
    } else {
      updated.add(id);
    }
    this.openFAQs.set(updated);
  }
}

